# Generated by Django 2.0.3 on 2018-04-14 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180411_1332'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='national_id',
            field=models.CharField(blank=True, max_length=200, verbose_name='national_id'),
        ),
    ]
