# Generated by Django 2.0.3 on 2018-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180414_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='national_id',
            field=models.CharField(max_length=200, unique=True, verbose_name='national_id'),
        ),
    ]
