# Generated by Django 2.0.3 on 2018-05-23 12:33

from django.db import migrations, models


def insert_defaults(apps, schema_editor):
    MembershipCategory = apps.get_model("membership_categories", "MembershipCategory")
    MembershipCategory(slug="terabyte" ).save()
    MembershipCategory(slug="gigabyte" ).save()
    MembershipCategory(slug="megabyte" ).save()
    MembershipCategory(slug="kilobyte" ).save()
    MembershipCategory(slug="microbyte" ).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(insert_defaults)
    ]
