# Generated by Django 2.0.3 on 2018-05-23 21:10

import colorfield.fields
from django.apps import apps
from django.db import migrations, models
import tisk.utils


def insert_defaults(apps, schema_editor):
    MembershipCategory = apps.get_model("membership_categories", "MembershipCategory")
    MembershipCategory(slug="terabyte" ).save()
    MembershipCategory(slug="gigabyte" ).save()
    MembershipCategory(slug="megabyte" ).save()
    MembershipCategory(slug="kilobyte" ).save()
    MembershipCategory(slug="microbyte" ).save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipCategory',
            fields=[
                ('slug', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('display_name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=tisk.utils.get_image_path)),
                ('color', colorfield.fields.ColorField(blank=True, max_length=18, null=True)),
            ],
        ),
        migrations.RunPython(insert_defaults)
    ]
