# Generated by Django 2.0.3 on 2018-05-28 07:26

from django.db import migrations, models
import tisk.utils


class Migration(migrations.Migration):

    dependencies = [
        ('membership_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membershipcategory',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, upload_to=tisk.utils.get_image_path),
        ),
    ]
