# Generated by Django 2.0.3 on 2018-05-28 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_categories', '0002_auto_20180528_0726'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipcategory',
            name='order_number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
