# Generated by Django 2.0.3 on 2018-05-22 21:48

from django.db import migrations, models

def insert_defaults(apps, schema_editor):
    MemberType = apps.get_model("member_types", "MemberType")
    MemberType(name="Investor Business").save()
    MemberType(name="Investor Individual").save()
    MemberType(name="Business").save()
    MemberType(name="Professional").save()
    MemberType(name="Student").save()
    MemberType(name="Child", active=False).save()


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RunPython(insert_defaults)
    ]
