# Generated by Django 2.0.3 on 2018-05-23 21:10

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import tisk.utils


def insert_defaults(apps, schema_editor):
    MemberType = apps.get_model("member_types", "MemberType")
    MemberType(name="Investor Business", membership_category_id="terabyte", type="Business").save()
    MemberType(name="Investor Individual", membership_category_id="terabyte", type="Individual").save()
    MemberType(name="Business", membership_category_id="gigabyte", type="Business").save()
    MemberType(name="Professional", membership_category_id="megabyte", type="Individual").save()
    MemberType(name="Student", membership_category_id="kilobyte", type="Individual").save()
    MemberType(name="Futures", membership_category_id="microbyte", active=False, type="Future").save()

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('membership_categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('monthly_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('share_capital', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=tisk.utils.get_image_path)),
                ('color', colorfield.fields.ColorField(blank=True, max_length=18, null=True)),
                ('type', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Business', 'Business'), ('Future', 'Future')], max_length=20, null=True)),
                ('membership_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='membership_categories.MembershipCategory')),
            ],
        ),
        migrations.RunPython(insert_defaults)
    ]
