# Generated by Django 2.0.3 on 2018-05-23 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member_types', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('other_names', models.CharField(max_length=255)),
                ('national_id', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50)),
                ('phone_number', models.EmailField(max_length=50)),
                ('business_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=255)),
                ('business_email', models.CharField(max_length=100)),
                ('business_phone_number', models.CharField(max_length=50)),
                ('contact_name', models.CharField(max_length=255)),
                ('contact_phone_number', models.CharField(max_length=50)),
                ('contact_position', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=100)),
                ('is_msf_active', models.BooleanField(default=False)),
                ('msf_account', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Suspended', 'Suspended')], default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='member_types.MemberType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_member', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('user', 'member_type')},
        ),
    ]
