# Generated by Django 2.0.3 on 2018-04-19 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member_types', '0002_auto_20180418_1723'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_msf_active', models.BooleanField(default=False)),
                ('msf_account', models.CharField(blank=True, max_length=50, null=True)),
                ('member_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='member_types.MemberType')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
