# Generated by Django 2.0.3 on 2018-05-30 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_is_registartion_fee_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='business_email',
        ),
    ]
